# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeggarJob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeggarJob

  pod “AFNetworking”, '~> 3.1.0’
  pod “MBProgressHUD”
  pod “SVProgressHUD”
  pod ‘MJExtension’,’~>3.0.13’
  pod ‘MJRefresh’, ’~>3.1.12’
  pod ‘Masonry’,’~>1.0.2’
  pod ‘SDWebImage’,’~>3.8.2’
  pod “WebViewJavascriptBridge”, '~> 5.0'
  

  target 'BeggarJobTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeggarJobUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
